MusicDigging/Mudig_FE

public/index.html
src/hooks/queries/useUserInfo.jsx
src/library/sweetAlert/sweetAlert.js
src/library/sweetAlert/sweetalert.module.css
src/pages/Signup/SignupDetail.jsx
src/pages/UserInfo/ChangePwForm.jsx
src/pages/UserInfo/UserLeaveForm.jsx

ex) feature/userInfo -> develop
#85
- 회원정보 입력 후 비밀번호 일치하면 회원탈퇴 진행
- 회원탈퇴시 탈퇴 확인 모달로 한번 더 물어보기
- 회원탈퇴 모달 sweetalert2 라이브러리로 구현 & 모달 컴포넌트화

회원탈퇴 페이지 기능구현

---

src/components/Loading/Loading.jsx
src/pages/CreatePlaylist/CreatePlaylist1.jsx
src/pages/CreatePlaylist/CreatePlaylist2.jsx
src/pages/CreatePlaylist/CreatePlaylist3.jsx
src/pages/CreatePlaylist/CreatePlaylistStyle.jsx

`feature/NewPlaylist/Create-> develop`
- 버튼 위치 겹치는 문제 수정
- 글자수 제한 및 표시 기능
- 로딩중 전환 시간 조절 0.7초 -> 0.5초

플리 생성 페이지 확인작업

---

src/components/Profile/MainPlayList.jsx
src/components/Profile/MainPlayListSection.jsx
src/components/Profile/PlayListSection.jsx
src/components/Profile/ProfileSection.jsx

`feature/Profile -> develop`
- 대표 플레이리스트 플리 목록 스크롤 잘림 수정
- 플레이리스트 정렬 최신순 default로 focus 효과 설정
- 뒤로가기 버튼 기능 추가

프로필 페이지 확인작업

---

src/components/PlaylistDetail/PlayListModify.jsx

feature/PlaylistModify -> develop
- 플리 수정 삭제 버튼 위치 수정
[수정 전]
[수정 후]

플리 수정 삭제 버튼 위치 수정

---

src/components/PlaylistDetail/CommentSection.jsx
src/components/PlaylistDetail/DetailList.jsx
src/components/PlaylistDetail/MusicPlayBar.jsx
src/components/PlaylistDetail/PlayListInfo.jsx
src/components/common/PlayList/PlayListItem.jsx
src/img/share-icon.svg
src/pages/PlaylistDetail/PlaylistDetail.jsx

`feature/PlaylistDetail -> develop`
- 플리 곡이 0개인 경우 처리 #94
- 플리 상세 음악목록 2개 이하일 때 확장버튼 숨김 #96
- 내 플리 아닐 때 더보기 버튼에서 좋아요 버튼으로 변경 #96
- 플리 상세 페이지 컴포넌트별 배경색 설정 #96

플리 상세 페이지 확인작업

---

src/components/Profile/FollowUserList.jsx
src/components/Profile/ProfileSection.jsx
src/components/common/User.jsx
src/hooks/queries/useFollow.jsx
src/pages/Profile/Follow.jsx

ex) feature/Follow -> develop
#62
- 프로필 페이지 버튼 클릭에 따라 화면 다르게 구현(useLocation에서 state 사용)
- 팔로잉일 때 버튼 클릭시 언팔로우, 팔로워일 때 버튼 클릭시 팔로잉
- 커스텀 훅 제작(post, delete라서 useMutation사용)

follow 페이지 기능구현

---

src/components/Home/MyPlayListTable.jsx
src/pages/PlaylistDetail/PlaylistDetail.jsx

ex) feature/Home -> develop
- 아이콘 사이즈 변경
- 배경색 변경

Style: 아이콘 크기 변경, 배경 색 변경

---

src/components/PlaylistDetail/PlayListModify.jsx

feature/PlaylistModify -> develop
- 플리 수정 페이지 배경 이미지에 맞게 스타일 수정

플리 수정 페이지 배경 이미지에 맞게 스타일 수정

---

src/pages/EditProfile/EditProfile.jsx
src/pages/Profile/Profile.jsx

`feature/Profile -> develop`
실수로 develop에서 작업한 내역은 해시링크를 달아두었습니다...ㅎㅎ
- id 고정값 원래대로 돌리기 41ad052ef50c9f9c2390adf5f32fef9ba9e75a24
- 팔로우 팔로잉 순서 통일 0b577583dc3e2552ce156ccfd63fdd9696b470aa
- 프로필 데이터 최신화해서 불러오기 (isFetching) 5649ac81c5ff6675ab8eeff920f51f0d6b32e424
플리 생성, 프로필 수정 후 프로필 이동 시 변경사항이 바로 반영될 수 있도록 수정
- 프로필 메인 부분 이미지 늘어나는 현상 수정
- 프로필 수정 현재 그대로 유지 시 `image`값을 request 보낼 formdata에서 제외
- 비공개 플리 다른 유저에게 안보이도록 필터링

프로필 페이지 확인작업 2차

---

src/components/Home/MyPlayListTable.jsx
src/pages/Home/Home.jsx
src/pages/Splash/Splash.jsx

ex) feature/Home -> develop
#61 , #105 
- 유저 데이터 받아서 화면에 보여주기
- 로그인 여부 확인해서 페이지 다르게 이동
- 아이콘 사이즈 변경

홈 화면, 스플래쉬 화면 기능추가

---

src/components/common/Form/AuthForm.jsx
src/components/common/Form/SignupForm.jsx
src/library/atom.js
src/pages/Login/Login.jsx
src/pages/Signup/Signup.jsx

ex) feature/Login -> develop
#116
- 이미 로그인한 유저라면 로그인/회원가입 접근 막기
- 체크박스 클릭 오류 해결
- 이메일 인증 메일 발송 시 토스트 메시지 보여주기

로그인/ 회원가입 사용자 개선 사항 

---

src/pages/CreatePlaylist/CreatePlaylistStyle.jsx

feature/NewPlaylist/Create-> develop
- 모바일 화면 잘림현상 수정

플리 생성, 플리 상세 모바일 화면 잘림현상 수정

---

src/pages/CreatePlaylist/CreatePlaylist1.jsx
src/pages/CreatePlaylist/CreatePlaylist3.jsx
src/pages/CreatePlaylist/CreatePlaylistStyle.jsx
src/pages/PlaylistDetail/PlaylistDetail.jsx

feature/NewPlaylist/Create-> develop
- 플리 생성 에러 발생 시 Input 데이터 초기화되는 문제 해결 #127
- Link 태그 disabled cursor 스타일 수정
- 처음 플리 생성 페이지 이미지 애니메이션 추가
- 플리 상세 페이지 배경색 조정

플리 생성, 플리 상세 수정

---

src/components/common/Modal/AddModal.jsx

ex) feature/randomMv -> develop
#125
- 랜덤뮤비 드롭다운 max-height 값 설정 & 스크롤 설정
드롭다운 활성화 시 arrow-icon 접기 모양으로 변경은 적용하려는데 자꾸 안되서.. 일단  max-height값이랑 스크롤 설정한거 pr 날립니다!

랜덤뮤비 페이지 스타일 설정 수정

---

src/components/EditProfile/SetRepPlaylist.jsx
src/components/Profile/MainPlayListSection.jsx
src/components/Profile/PlayListSection.jsx
src/components/common/PlayList/PlayListItem.jsx
src/pages/Profile/Profile.jsx

분명 다 수정했다고 생각했는데 자꾸 생기는 매직..
우선 QA에 올라온 부분은 모두 처리했습니다
제가 놓친 부분이 또 있을 수 있기에...코드 확인 및 실행 피드백 꼭 부탁드리고 싶어요-
- 프로필 수정 페이지 대표 플레이리스트 공개 플리만 설정 가능하도록 변경, 플리 없을 시 문구 처리
- 좋아요한 플레이리스트 목록 추가, liked_playlists 데이터 없을 경우 숨김

프로필 페이지 확인작업 4차

---

src/components/common/Form/SignupForm.jsx
src/components/common/Toast.jsx
src/hooks/queries/useUserInfo.jsx
src/library/apis/api.js
src/pages/SetProfile/SetProfile.jsx
src/pages/Signup/SignupDetail.jsx

ex) feature/Login -> develop
- Toast 메시지 디자인 시안 적용
- framer-motion 사용하여 Toast 메시지 애니메이션 효과 구현
- otp post 요청코드 useMutation 사용으로 변경
- 프로필등록 post 요청코드 useMutation 사용으로 변경

유저정보 관련 리팩토링

---

src/components/common/NavBar/NavBar.jsx

feature/Home -> develop
- NavBar 컴포넌트에서 발생하는 경고 메시지 해결

Fix: Styled-components props 에러

---

src/components/common/Modal/Modal.jsx

feature/PlaylistModify -> develop
- 플리 수정 모달 UI 수정

Style: 플리 수정 모달 UI 수정

---

src/components/PlaylistDetail/CommentForm.jsx
src/components/PlaylistDetail/CommentItem.jsx
src/components/PlaylistDetail/CommentList.jsx
src/components/PlaylistDetail/PlayListModify.jsx
src/pages/PlaylistDetail/Comment.jsx
src/pages/PlaylistDetail/CommentStyle.jsx
src/pages/PlaylistDetail/PlaylistDetail.jsx
src/pages/PlaylistDetail/Reply.jsx

#146 
1. 플리 상세 페이지 & 댓글/답글 페이지 뒤로가기 버튼 위치 맞춤 
-> UI 시안에서 버튼 위치가 다르게 되어 있던 부분 통일
2. 수정 상태에서 뒤로가기 이동 시 input 내용 그대로 유지되는 현상
-> 뒤로가기 버튼 클릭 이벤트에서 input 데이터 삭제
3. 답글 삭제 시 undefined 오류 
-> 답글 데이터 체이닝 연산자 `?` 사용   
4. 플리 수정 페이지 스크롤 안됨
-> `overflow-y : scroll` 적용
5. 댓글 인풋&버튼 높이값 통일
6. 댓글 확장 버튼 기준값 수정 
7. 답글 페이지 댓글/답글 영역 구분(border)

플리 상세/수정 페이지 스타일 버그 및 오류 수정

---

src/components/Profile/ProfileSection.jsx
src/img/background-img.svg
src/pages/Home/Home.jsx
src/pages/Home/HomeStyle.jsx
src/pages/Splash/Splash.jsx

ex) feature/Home -> develop
#136 
- 스플래쉬 페이지 토큰 인증
로그아웃 후 스플래쉬 페이지에서 메인페이지로 이동후 404페이지로 이동되는 문제
토큰 검증에 문제라고 생각해서 스플래쉬 페이지 코드에서 문제가 있는지 확인했으나 그 코드 문제가 아님
로그아웃에서 로컬스토리지에 저장되어 있는 값을 삭제하는 부분에 문제가 있는지 확인했으나 잘 삭제됨
전역에서 관리하는 isLoginAtom에 문제가 있는지 사용하는 모든 코드를 점검했으나 관련 없었음
문제의 원인은 로그아웃하고 로컬스토리지에 있는 값을 잘 삭제했으나 그 상태를 업데이트하는 코드가 없었기 때문
해결 : 'recoil'의 { useSetRecoilState }를 사용해 삭제한 뒤 상태를 업데이트 하는 코드를 작성
- 스플래쉬 캐릭터 이미지 사파리에서 안보이는 문제
사파리에서 bottom:-600%;라고 작성한 코드가 적용이 되지 않아서 발생한 문제
- 전체 페이지 배경 그라데이션 컬러가 진하다는 디자이너의 QA
- 홈페이지에서 내가 만든 플리가 없을 때 UI, 플리 생성 유도 버튼

스플래쉬, 홈 페이지 오류 수정 및 기능 추가

---

src/components/Search/SearchInput.jsx
src/pages/Search/SearchStyle.jsx

feature/Search -> develop
- safari에서 버튼 아래로 내려가는 현상 수정

Style: 검색 버튼 스타일 수정

---

src/components/common/Toast.jsx
src/pages/EditProfile/EditProfile.jsx
src/pages/Login/Login.jsx
src/pages/PlaylistDetail/Comment.jsx
src/pages/PlaylistDetail/CommentStyle.jsx
src/pages/PlaylistDetail/PlaylistDetail.jsx
src/pages/PlaylistDetail/Reply.jsx
src/pages/Profile/Profile.jsx
src/pages/RandomMusic/RandomMusic.jsx
src/pages/SetProfile/SetProfile.jsx
src/pages/Signup/SignupDetail.jsx

feature/PlaylistModify -> develop
- 반응형 작업으로 인해 토스트 메시지 너비 안맞는 부분 수정
- 기존에 토스트 메시지를 사용하는 모든 파일에서 ToastBox로 Toast 컴포넌트를 감싸서 사용했으나 이를 Toast 컴포넌트에 해당 스타일 코드를 추가하여 중복되는 코드 제거함
❗️한번씩 토스트 메시지 나타나는 부분 확인 부탁드립니다 ❗️

QA) Toast 스타일 수정

---

src/components/EditProfile/SetProfileImage.jsx
src/components/PlaylistDetail/MusicWave.jsx
src/components/common/PlayList/PlayListItem.jsx
src/components/common/Toast.jsx
src/pages/EditProfile/EditProfile.jsx
src/pages/EditProfile/EditProfileStyle.jsx
src/pages/Login/Login.jsx
src/pages/PlaylistDetail/Comment.jsx
src/pages/PlaylistDetail/CommentStyle.jsx
src/pages/PlaylistDetail/PlaylistDetail.jsx
src/pages/PlaylistDetail/Reply.jsx
src/pages/Profile/Profile.jsx
src/pages/RandomMusic/RandomMusic.jsx
src/pages/SetProfile/SetProfile.jsx
src/pages/Signup/SignupDetail.jsx

feature/Profile -> develop
- [마이페이지-> 프로필 수정 페이지 -> 뒤로가기 -> 마이페이지 -> 뒤로가기 -> 프로필 수정 페이지 (무한루프)
- 관심사 버튼 3개 이상 토스트 메시지 바로 실행 안됨 -> 프로필 수정 페이지 토스트 설정
-  프로필 수정 이미지 업로드 시 경고 토스트 메시지

프로필 페이지 QA

---

src/components/PlaylistDetail/CommentSection.jsx
src/pages/PlaylistDetail/PlaylistDetail.jsx

feature/PlaylistDetail -> develop
- 음악 재생 중 막대 가운데 px 수정 => 막대 두께가 작아서 화면이 작을 시 보이는 현상이라 두께를 수정했습니다
- 음악 목록 없을 때 보이는 컴포넌트 가운데로 위치 수정
- 댓글 필터링 기준 수정 (comments.length > 0일 때 필터링)
- 🙅‍♀️ 모바일에서 노래 재생하면 재생 아이콘은 애니메이션이 작동되는데 실제로 노래는 재생이 안됨 => 제 폰에서도 발생하는데 브라우저  정책에 따라 차단될 수 있다고 합니다. 수정은 어려울 것 같아요..

플리 상세 페이지 QA

---

src/components/common/Form/SignupForm.jsx

feature/Signup -> develop
- 회원가입 폼 인증번호 필수 입력 기능 구현

회원가입 폼 인증번호 필수 입력 기능 구현

---

README.md
src/library/apis/axiosInstance.js

- 테스트 기간동안은 임의로 자동 로그인 없이도 로그인 연장

Fix: 로그인 이후 페이지 찾을 수 없음 버그 수정

---

README.md
src/library/apis/axiosInstance.js

401 토큰 에러시 로컬스토리 clear 적용

---

src/components/common/Input/AuthInput.jsx
src/components/common/Input/ProfileInput.jsx
src/components/common/Input/SignupInput.jsx
src/pages/Login/Login.jsx
src/pages/SetProfile/SetProfile.jsx

ex) feature/userInfo -> develop
-  유저정보 관련 입력 input의 자동완성 해제
-  프로필 설정 시 기본적으로 관심사는 3개까지 설정할 수 있다고 문구 설정 
-  아이디 비밀번호 찾기 기능 미구현 상태임을 알려주기
추가로 지난번 회의때 Ios에서 접근시 input창 선택시 포커스 되는 문제에 대해서는 이야기를 안나눈거 같은데 어떻게 하면 좋을까요?? 
아래 블로그에 해결 방법 알려주고있는데 제일 간편한건 인풋 폰트 크기를 16px로 변경하는게 좋을 것 같아요
[[iOS/Safari] 의 focus 확대 방지하기](https://velog.io/@jungsu/iOSSafari-input-%EC%9D%98-focus-%ED%99%95%EB%8C%80-%EB%B0%A9%EC%A7%80%ED%95%98%EA%B8%B0)

유저정보 관련 유저 피드백 반영

---

README.md
src/components/common/Input/AuthInput.jsx
src/components/common/Input/ProfileInput.jsx
src/components/common/Input/SignupInput.jsx
src/library/apis/axiosInstance.js

ex) feature/develop -> main
-유저정보 관련 입력 input의 자동완성 해제
-프로필 설정 시 기본적으로 관심사는 3개까지 설정할 수 있다고 문구 설정
-아이디 비밀번호 찾기 기능 미구현 상태임을 알려주기

유저정보 관련 변경사항 main push 

---

src/components/common/Modal/Modal.jsx
src/components/common/Toast.jsx
src/pages/PlaylistModify/PlaylistModify.jsx
src/styles/GlobalStyle.jsx

feature/playlistModify -> develop
- 플리 수정 모달 바뀐 디자인 반영
- 수정 모달에서 제목, 콘텐츠가 빈 경우 toast로 경고 메시지 출력

플리 수정 모달 변경 사항

---

src/components/Search/SearchInput.jsx
src/components/Search/SearchResultAll.jsx
src/components/Search/SearchResultByType.jsx
src/components/Search/SearchResultTitle.jsx
src/pages/Search/SearchResult.jsx

feature/Search -> develop
- 플리,노래 탭 버튼 추가

플리,노래 탭 버튼 추가

---

package-lock.json
package.json
src/components/PlaylistDetail/PlayListInfo.tsx
src/components/PlaylistDetail/PlayListModify.tsx
src/components/Search/RecentSearch.tsx
src/components/Search/SearchInput.tsx
src/components/Search/SearchNav.tsx
src/components/Search/SearchResultAll.tsx
src/components/Search/SearchResultByType.tsx
src/components/Search/SearchResultTitle.tsx
src/components/common/Modal/Modal.tsx
src/hooks/queries/useSearch.tsx
src/library/atom.ts
src/pages/PlaylistModify/PlaylistModify.tsx
src/pages/Search/Search.tsx
src/pages/Search/SearchResult.tsx
src/types/custom.d.ts
src/types/playlist.ts
src/types/searchResult.ts
src/types/user.ts

refactor/jisu -> develop
- 타입스크립트로 수정

타입스크립트로 수정

---

src/components/common/Button/Button.tsx
src/components/common/Form/AuthForm.tsx
src/components/common/Form/SignupForm.tsx
src/hooks/queries/useRandomMv.tsx
src/hooks/queries/useUserInfo.tsx
src/hooks/ussPasswordToggle.tsx
src/library/apis/api.ts
src/pages/Login/Login.tsx
src/pages/RandomMusic/RandomMusic.tsx

ex) refactor/seojun -> typescript
- 타입스크립트 업데이트

타입스크립트 업데이트

---

src/hooks/queries/useUserInfo.tsx
src/pages/SetProfile/SetProfile.tsx

ex) feature/seojun -> typescript
- 기능
- 기능

유저정보& 프로필 설정 타입 업데이트

---

src/components/PlaylistDetail/PlayListInfo.tsx
src/components/PlaylistDetail/PlayListModify.tsx
src/components/Profile/MainPlayListSection.tsx
src/components/common/PlayList/PlayList.tsx
src/components/common/PlayList/PlayListItem.tsx
src/hooks/queries/usePlaylist.tsx
src/library/atom.ts
src/pages/NotFound/NotFound.tsx
src/pages/PlaylistDetail/PlaylistDetail.tsx
src/pages/PlaylistSummary/PlaylistSummary.tsx
src/pages/Profile/Profile.tsx
src/pages/Search/SearchResult.tsx

Refactor/jisu -> typescript
- 타입스크립트로 변경

Refactor: 타입스크립트로 수정

---

src/components/common/Form/SignupForm.tsx
src/components/common/Input/AuthInput.tsx
src/components/common/Input/ProfileInput.tsx
src/components/common/Input/SignupInput.tsx
src/components/common/Modal/AddModal.tsx
src/library/atom.ts
src/pages/Login/Login.tsx
src/pages/RandomMusic/RandomMusic.tsx
src/pages/SetProfile/SetProfile.tsx
src/pages/Signup/Signup.tsx
src/pages/Signup/SignupDetail.tsx
src/pages/UserInfo/ChangePwForm.tsx
src/pages/UserInfo/UserLeaveForm.tsx
src/types/input.ts
src/types/user.ts

Refactor: 타입스크립트 업데이트

---

src/components/Home/MyPlayListTable.tsx
src/components/Home/PlayListTable.tsx
src/components/Profile/FollowUserList.tsx
src/components/common/User.tsx
src/hooks/queries/useFollow.tsx
src/hooks/queries/useHome.tsx
src/library/atom.ts
src/pages/EventPage/EventPage.tsx
src/pages/Home/Home.tsx
src/pages/Home/Intro.tsx
src/pages/Home/MorePlaylist.tsx
src/pages/NotFound/NotFound.tsx
src/pages/Profile/Follow.tsx
src/pages/Splash/Splash.tsx

ex) refactor/yeji -> typescript
- 홈, 이벤트, 스플래쉬, 팔로우 페이지 타입스크립트 마이그레이션

홈, 이벤트, 스플래쉬, 팔로우 페이지 타입스크립트 마이그레이션

---

src/components/common/Input/ProfileInput.tsx
src/components/common/Modal/AddModal.tsx
src/library/ImgCompression.ts
src/pages/EditProfile/EditProfile.tsx
src/pages/SetProfile/SetProfile.tsx
src/pages/UserInfo/ChangePwForm.tsx
src/pages/UserInfo/UserLeaveForm.tsx
src/types/profile.ts

타입스크립트 업데이트 

---

src/components/Home/MyPlayListTable.tsx
src/components/Home/PlayListTable.tsx
src/components/Profile/FollowUserList.tsx
src/components/common/NavBar/NavBar.tsx
src/hooks/queries/useHome.tsx
src/pages/Home/Home.tsx
src/pages/Home/Intro.tsx
src/pages/Home/MorePlaylist.tsx
src/pages/Profile/Follow.tsx

refactor/yeji -> typescript
컨벤션에 맞게 interface 타입명 수정

ts interface 네이밍 수정

---

src/components/PlaylistDetail/DetailList.tsx
src/components/PlaylistDetail/PlayListInfo.tsx
src/components/PlaylistDetail/PlayListModifyList.tsx
src/components/Search/SearchInput.tsx
src/components/Search/SearchResultAll.tsx
src/components/Search/SearchResultByType.tsx
src/components/Search/SearchResultTitle.tsx
src/components/common/Button/Button.tsx
src/components/common/Modal/Modal.tsx
src/components/common/PlayList/PlayListItem.tsx
src/pages/PlaylistDetail/PlaylistDetail.tsx
src/pages/PlaylistModify/PlaylistModify.tsx
src/pages/PlaylistSummary/PlaylistSummary.tsx
src/pages/Search/SearchResult.tsx

웹 접근성 개선, 스타일 수정

---

src/components/common/Form/AuthForm.tsx
src/hooks/useSocialLogin.tsx
src/pages/Login/Login.tsx
src/pages/Signup/Signup.tsx

로그인 페이지 리팩토링 

---

src/components/EditProfile/SetProfileImage.tsx
src/components/common/Form/SignupForm.tsx
src/components/common/Input/ProfileInput.tsx
src/library/atom.ts
src/pages/Login/Login.tsx
src/pages/Login/LoginStlye.tsx
src/pages/SetProfile/SetProfile.tsx
src/pages/SetProfile/SetProfileStyle.tsx
src/pages/Signup/Signup.tsx
src/pages/Signup/SignupDetail.tsx

ex) refacotr/seojun-> main
- 회원가입/ 프로필 설정 리팩토링 내용 반영

회원가입/ 프로필 설정 리팩토링 내용 반영

---

src/components/Home/PlayListTable.tsx
src/pages/Home/HomeStyle.tsx

home 여백 조정
